services:
  storage:
    image: redis
    volumes:
      - ./data:/data

  counter:
    image: node:19.9-alpine3.16
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - storage
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    ports:
      - 80:3000
    command: ["npm", "run", "dev"]

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/