services:
  storage:
    image: redis
    volumes:
      - ./data:/data
  counter:
    image: node:19.9-alpine3.16
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - storage
    environment:
      - PORT=3000
      - REDIS_URL=redis://storage
    ports:
      - 80:3000
    command: ["npm", "run", "dev"]